# Site settings
title: Júnior César Abreu - Desenvolvedor de Software - São Geraldo, MG (Zona da Mata)
description: Fullstack Developer Freelancer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
keywords: junior cesar abreu, junior cesar, são geraldo, developer, html, html5, css, css3, js, javascript, jquery, web development, freelancer, jobs, desenvolvedor front-end freelancer, front-end, back-end, full stack

# User settings
username: Júnior César Abreu
user_description: Vou colocar uma descrição aqui ainda.
user_title: Software Developer
email: "juniorcesarabreu", "live.com"
# twitter_username: lorem_ipsum
github_username:  juniorcesarabreu
gplus_username:  104674023050699476535
facebook_username: juniorcesarabreu.sg
aboutme_username: juniorcesarabreu
linkedin_username: juniorcesarabreu

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules', 'nbproject']
